#!/usr/bin/env python3
// Delete by match
db.school.deleteMany(
    { name: "Holberton school" }
)
root@385e8ae36597:/alx-backend-storage/0x01-NoSQL# cat > 8-all.py
#!/usr/bin/env python3
""" MongoDB Operations with Python using pymongo """


def list_all(mongo_collection):
    """ List all documents in Python """
    documents = mongo_collection.find()

    if documents.count() == 0:
        return []

    return documents
